// front-react/src/views/home/Home.jsx
import React, { useState } from "react";
import "./Home.css";

export default (props) => {
  let [ legenda, setLegenda ] = useState("React");

  function resetLegenda() {
    setLegenda("React");
  }

  return (
    <div className="home">
      <h1>{props.msg}</h1>
      <h2>{legenda}</h2>
      <input value={legenda} onChange={e => setLegenda(e.target.value)} />
      <button onClick={ resetLegenda }>Reset Legenda</button>
    </div>
  );
};

// front-vue/src/views/home/Home.vue
<template>
  <div>
    <h1>{{ msg }}</h1>
    <h2>{{ legenda }}</h2>
    <input type="text" v-model="legenda" />
    <button @click="resetLegenda">Reset Legenda</button>
  </div>
</template>

<script>
export default {
  props: ["msg"],
  data: function() {
    return {
      legenda: "Vue",
    };
  },
  methods: {
    resetLegenda() {
      this.legenda = "Vue";
    },
  },
};
</script>

<style>
</style>
