// front-angular/src/app/views/home/home.component.ts
import { Component, OnInit, Input } from "@angular/core";

@Component({
  selector: "app-home",
  templateUrl: "./home.component.html",
  styleUrls: ["./home.component.css"],
})
export class HomeComponent implements OnInit {
  @Input() msg: string;
  legenda: string = "Angular";

  constructor() {}

  ngOnInit(): void {}

  resetLegenda(): void {
    this.legenda = "Angular";
  }
}

// front-react/src/views/home/Home.jsx
import React, { useState } from "react";
import "./Home.css";

export default (props) => {
  let [ legenda, setLegenda ] = useState("React");

  function resetLegenda() {
    setLegenda("React");
  }

  return (
    <div className="home">
      <h1>{props.msg}</h1>
      <h2>{legenda}</h2>
      <input value={legenda} onChange={e => setLegenda(e.target.value)} />
      <button onClick={ resetLegenda }>Reset Legenda</button>
    </div>
  );
};
